### ISSUE TITLE
Layout conflict with fof best answer plugin

### ISSUE THREAD

**Issue by westindiantech** [ramesh-dada/mobile-flarum-newdiscuss#1]
Hi, i've enabled the plugin on my forum and it fits nicely until I enable friends of forum plugin for best answer.

Once enabled the mobile start discussion button gets bumped to the next line and is no longer centered.

Is there anything that can be done to shift its placement above or below centered?

**Comment by ramesh-dada** [comment]
@westindiantech Oh Thanks for reporting this it will be fixed very soon and now I will add the button before the toolbar but then it will look too big so I am also adding search if someone will click on search then search modal will open,
Something like this, just want to confirm according to you is it good or not?
![image](https://user-images.githubusercontent.com/75124237/132158700-85b0a949-9b9d-4c6b-9309-d7e43f29c046.png)

**Comment by westindiantech** [comment]
Hi thank you for making the adjustment, Yes that should work.  Let me ask, is it possible to hook into the FoF Follow Tags so there could be a follow button (icon only), ask a question (icon and text), search button (icon only)?

**Comment by ramesh-dada** [comment]
> Hi thank you for making the adjustment, Yes that should work. Let me ask, is it possible to hook into the FoF Follow Tags so there could be a follow button (icon only), ask a question (icon and text), search button (icon only)?

Can you explain properly, You want something like follow button then discussion button and then search button right? But It will take time to hook into fof tags.

**Comment by ramesh-dada** [comment]
Hello I think all this things are taking too much space so what do you think about this simple one see
![](https://androidexample365.com/content/images/2018/12/FloatingActionButtonExpandable.gif)

**Comment by westindiantech** [comment]
> > Hi thank you for making the adjustment, Yes that should work. Let me ask, is it possible to hook into the FoF Follow Tags so there could be a follow button (icon only), ask a question (icon and text), search button (icon only)?
> 
> Can you explain properly, You want something like follow button then discussion button and then search button right? But It will take time to hook into fof tags.

I was just asking if it made sense. Follow - Ask - Search as for an enduser perspective

**Comment by westindiantech** [comment]
> Hello I think all this things are taking too much space so what do you think about this simple one see
> ![](https://camo.githubusercontent.com/be8d7ad3b3df3202c63d8b1b5017bcd95c6aa10d5d216517e49a2c5be42f3add/68747470733a2f2f616e64726f69646578616d706c653336352e636f6d2f636f6e74656e742f696d616765732f323031382f31322f466c6f6174696e67416374696f6e427574746f6e457870616e6461626c652e676966)

Hi this looks good, and most advance forum users will enjoy using such an option but in my personal experience the average user will ignore it, your current button integration is clear and straight to the point why i enjoy using it.

**Comment by ramesh-dada** [comment]
@westindiantech Fixed in latest version.
Don't forget to clear cache.
